/*

package ThirdActivity;

import FirstActivity.CustomException;
import FirstActivity.Person;

public class NameException {
    public static void checkDigitsInString(String Name) throws CustomException {

        for (int i = 0; i < Person.length; i++) {


            Character.isLetter(amazing.charAt(7));

            //Creating and throwing an instance of CustomException
            //this ensures that CustomException is thrown
            throw new CustomException();
        }
    }

    public static void main(String arg[]) {
        //Since CustomException is a checked exception, it's mandatory to call setAge method
        //inside a try catch block. Else the code would not compile.
        //2 - call setAge method with -1 as its parameter and surround this with a try catch block
        try {

        } catch (CustomException ce) {
            System.out.println("Age cannot be zero " + ce);
            System.out.println(ce.getMessage());
        }

    }
}

*/
